---
spring:
  profiles: consul-producer-1
  application:
    name: spring-cloud-consul-producer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: spring-cloud-consul-producer
server:
  port: 10071
management:
  endpoints:
    web:
      exposure:
        include: '*'
---
spring:
  profiles: consul-producer-2
  application:
    name: spring-cloud-consul-producer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: spring-cloud-consul-producer
server:
  port: 10072
management:
  endpoints:
    web:
      exposure:
        include: '*'